use_frameworks!

target 'Phaedo_Example' do
  platform :ios, '9.0'

  pod 'Phaedo', :path => '../'

  target 'Phaedo_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.10'
  pod 'Nimble', '~> 5.0'
  end
end
